
[functions.register]
enabled = true
verify_jwt = false
import_map = "./functions/register/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/register/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/register/*.html" ]

[functions.login]
enabled = true
verify_jwt = false
import_map = "./functions/login/deno.json"
entrypoint = "./functions/login/index.ts"

[functions.files]
enabled = true
verify_jwt = false
import_map = "./functions/files/deno.json"
entrypoint = "./functions/files/index.ts"

[functions.participant]
enabled = true
verify_jwt = false
import_map = "./functions/participant/deno.json"
entrypoint = "./functions/participant/index.ts"

[functions.course_type]
enabled = true
verify_jwt = false
import_map = "./functions/course_type/deno.json"
entrypoint = "./functions/course_type/index.ts"

[functions.course_mode]
enabled = true
verify_jwt = false
import_map = "./functions/course_mode/deno.json"
entrypoint = "./functions/course_mode/index.ts"

[functions.course_theme]
enabled = true
verify_jwt = false
import_map = "./functions/course_theme/deno.json"
entrypoint = "./functions/course_theme/index.ts"

[functions.course]
enabled = true
verify_jwt = false
import_map = "./functions/course/deno.json"
entrypoint = "./functions/course/index.ts"

[functions.instructor]
enabled = true
verify_jwt = false
import_map = "./functions/instructor/deno.json"
entrypoint = "./functions/instructor/index.ts"

[functions.schedule]
enabled = true
verify_jwt = false
import_map = "./functions/schedule/deno.json"
entrypoint = "./functions/schedule/index.ts"
