create table if not exists public.participants (
  id integer primary key,
  name text not null,
  identity_number text not null,
  gender text not null,
  phone_number text not null,
  email text not null,
  date_of_birth date not null,
  religion text not null,
  address text not null,
  job_position text not null,
  job_company text not null,
  education text not null,
  cr_number text not null,
  passport_photo text not null,
  identity_card text not null,
  tax_number text not null,
  curiculum_vitae text not null,
  employment_certificate text not null,
  medical_certificate text not null,
  integrity_pact text not null,
  degree_certificate text not null,
  created_at timestamptz not null default now()
);
